import XCTest
@testable import PiPTidyCore

final class CoreTests:XCTestCase {
    func testCoordinateRoundTripAcrossNegativeDesktop(){let desktop=CGRect(x:-1440,y:-900,width:4480,height:2860);let r=CGRect(x:-1000,y:200,width:640,height:360);XCTAssertEqual(CoordinateConverter.globalTopLeftToAppKit(CoordinateConverter.appKitToGlobalTopLeft(r,desktop:desktop),desktop:desktop),r)}
    func testRetinaUsesPointsNotPixels(){let s=ScreenGeometry(frame:CGRect(x:0,y:0,width:1512,height:982),visibleFrame:CGRect(x:0,y:40,width:1512,height:900),scale:2);XCTAssertEqual(s.visibleFrame.width,1512)}
    func testClampAndCorners(){let v=CGRect(x:-100,y:20,width:1000,height:700);let r=CoordinateConverter.corner(1,size:CGSize(width:300,height:200),visible:v);XCTAssertEqual(r.maxX,v.maxX-12);XCTAssertTrue(v.contains(r))}
    func testScoringAndTieDeterminism(){let s=DefaultCandidateScorer();let good=AXWindowSnapshot(id:"a",pid:1,owner:"Browser",subrole:"AXFloatingWindow",frame:CGRect(x:0,y:0,width:480,height:270),capabilities:.init(movable:true,resizable:true));let bad=AXWindowSnapshot(id:"b",pid:1,owner:"Browser",frame:CGRect(x:0,y:0,width:50,height:1200));XCTAssertGreaterThan(s.score(good,cg:nil).total,s.score(bad,cg:nil).total);XCTAssertEqual(s.score(good,cg:nil),s.score(good,cg:nil))}
    func testCorrelationRejectsAmbiguity(){let a=AXWindowSnapshot(id:"a",pid:7,owner:"x",frame:CGRect(x:1,y:2,width:3,height:4));let c=CGWindowSnapshot(id:1,pid:7,owner:"x",frame:a.frame!,layer:1);XCTAssertNil(WindowCorrelator.match(a,cg:[c,c]));XCTAssertEqual(WindowCorrelator.match(a,cg:[c])?.id,1)}
    func testPlacementSearchesEveryCellAndMaximizesSize(){var costs=[Float](repeating:10,count:100);for y in 2..<8{for x in 3..<9{costs[y*10+x]=0}};let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:costs);let r=PlacementOptimizer.best(map:map,aspectRatio:1,minSize:CGSize(width:20,height:20),maxSize:CGSize(width:100,height:100),costBudget:0);XCTAssertEqual(r?.frame,CGRect(x:30,y:20,width:60,height:60));XCTAssertEqual(r?.area,3600)}
    func testPlacementTieBreaksTopThenLeft(){let map=PlacementMap(bounds:CGRect(x:-20,y:5,width:40,height:20),width:4,height:2,costs:[Float](repeating:0,count:8));let r=PlacementOptimizer.best(map:map,aspectRatio:1,minSize:CGSize(width:10,height:10),maxSize:CGSize(width:10,height:10),costBudget:0);XCTAssertEqual(r?.frame.origin,CGPoint(x:-20,y:5))}
    func testPlacementShrinksToAvoidHighImportancePixels(){var costs=[Float](repeating:1,count:100);for y in 0..<5{for x in 0..<5{costs[y*10+x]=0}};let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:costs);let r=PlacementOptimizer.best(map:map,aspectRatio:1,minSize:CGSize(width:20,height:20),maxSize:CGSize(width:100,height:100),costBudget:1,highCostThreshold:0.5,maxHighCostFraction:0);XCTAssertEqual(r?.frame,CGRect(x:0,y:0,width:50,height:50))}
    func testScoringMapAndHeatmapDimensions(){var pixels=[UInt8](repeating:0,count:4*4*4);for index in stride(from:0,to:pixels.count,by:4){pixels[index]=255;pixels[index+3]=255};let provider=CGDataProvider(data:Data(pixels) as CFData)!;let image=CGImage(width:4,height:4,bitsPerComponent:8,bitsPerPixel:32,bytesPerRow:16,space:CGColorSpaceCreateDeviceRGB(),bitmapInfo:CGBitmapInfo(rawValue:CGImageAlphaInfo.premultipliedLast.rawValue),provider:provider,decode:nil,shouldInterpolate:false,intent:.defaultIntent)!;let map=ScoringMapGenerator.make(image:image,bounds:CGRect(x:10,y:20,width:4,height:4));XCTAssertEqual(map?.costs.count,16);let heatmap=map.flatMap{ScoringMapGenerator.heatmap($0,placement:CGRect(x:11,y:21,width:2,height:2))};XCTAssertEqual(heatmap?.width,4);XCTAssertEqual(heatmap?.height,4)}
    func testForegroundPriorityProtectsCompactFrontWindow(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0,count:100));let front=CGWindowSnapshot(id:1,pid:10,owner:"Editor",frame:CGRect(x:0,y:0,width:50,height:50),layer:0);let back=CGWindowSnapshot(id:2,pid:11,owner:"Desktop",frame:CGRect(x:0,y:0,width:100,height:100),layer:0);let weighted=ScoringMapGenerator.applyingForegroundPriority(map,windows:[front,back],excludingPID:99,excludingWindowID:nil);XCTAssertGreaterThan(weighted.cost(atX:1,y:1),0);XCTAssertEqual(weighted.cost(atX:9,y:9),0)}
    func testDesktopClearanceZerosWallpaperButPreservesWindowContent(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0.8,count:100));let window=CGWindowSnapshot(id:1,pid:10,owner:"Editor",frame:CGRect(x:0,y:0,width:50,height:50),layer:0);let cleared=ScoringMapGenerator.applyingDesktopClearance(map,windows:[window],excludingPID:99,excludingWindowID:nil);XCTAssertEqual(cleared.cost(atX:1,y:1),0.8);XCTAssertEqual(cleared.cost(atX:9,y:9),0)}
    func testDesktopClearanceIgnoresPiPAndOwnWindows(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0.8,count:100));let pip=CGWindowSnapshot(id:1,pid:10,owner:"Browser",frame:map.bounds,layer:1);let own=CGWindowSnapshot(id:2,pid:20,owner:"PiP Tidy",frame:map.bounds,layer:0);let cleared=ScoringMapGenerator.applyingDesktopClearance(map,windows:[pip,own],excludingPID:20,excludingWindowID:1);XCTAssertTrue(cleared.costs.allSatisfy{$0 == 0})}
    func testDesktopClearanceIgnoresNonstandardOverlayLayers(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0.8,count:100));let overlay=CGWindowSnapshot(id:1,pid:10,owner:"Overlay",frame:map.bounds,layer:20);let cleared=ScoringMapGenerator.applyingDesktopClearance(map,windows:[overlay],excludingPID:99,excludingWindowID:nil);XCTAssertTrue(cleared.costs.allSatisfy{$0 == 0})}
    func testDesktopClearancePreservesCompactFloatingWindows(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0.8,count:100));let panel=CGWindowSnapshot(id:1,pid:10,owner:"Panel",frame:CGRect(x:0,y:0,width:30,height:30),layer:20);let cleared=ScoringMapGenerator.applyingDesktopClearance(map,windows:[panel],excludingPID:99,excludingWindowID:nil);XCTAssertEqual(cleared.cost(atX:1,y:1),0.8);XCTAssertEqual(cleared.cost(atX:9,y:9),0)}
    func testWindowClearanceKeepsAGapAroundContent(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:100,height:100),width:10,height:10,costs:[Float](repeating:0.8,count:100));let window=CGWindowSnapshot(id:1,pid:10,owner:"Terminal",frame:CGRect(x:0,y:0,width:50,height:100),layer:0);let cleared=ScoringMapGenerator.applyingDesktopClearance(map,windows:[window],excludingPID:99,excludingWindowID:nil,clearance:10);XCTAssertEqual(cleared.cost(atX:5,y:5),0.8);XCTAssertEqual(cleared.cost(atX:6,y:5),0)}
    func testPlacementStabilityRejectsTinyNudges(){let current=CGRect(x:100,y:100,width:480,height:270);XCTAssertFalse(PlacementStability.shouldMove(from:current,to:CGRect(x:108,y:106,width:484,height:272)));XCTAssertTrue(PlacementStability.shouldMove(from:current,to:CGRect(x:140,y:100,width:480,height:270)));XCTAssertTrue(PlacementStability.shouldMove(from:current,to:CGRect(x:100,y:100,width:520,height:292)))}
    func testScoringMapCapsAnalysisResolution(){let color=CGColorSpaceCreateDeviceRGB();let context=CGContext(data:nil,width:640,height:360,bitsPerComponent:8,bytesPerRow:0,space:color,bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue)!;let map=ScoringMapGenerator.make(image:context.makeImage()!,bounds:CGRect(x:0,y:0,width:2560,height:1440));XCTAssertEqual(map?.width,320);XCTAssertEqual(map?.height,180)}
    func testPiPDetectorUsesExplicitTitleAndDeterministicScore(){let ordinary=WindowSnapshot(ax:.init(id:"a",pid:1,owner:"Browser",title:"Video"),cg:nil,score:.init([.init("score",100,"ordinary")]));let pipLow=WindowSnapshot(ax:.init(id:"c",pid:1,owner:"Chrome",title:"Picture in Picture"),cg:nil,score:.init([.init("score",10,"pip")]));let pipHigh=WindowSnapshot(ax:.init(id:"b",pid:2,owner:"Firefox",title:"Picture-in-Picture"),cg:nil,score:.init([.init("score",20,"pip")]));XCTAssertEqual(PiPDetector.detect(in:[ordinary,pipLow,pipHigh])?.id,"b")}
    func testTemporalStalenessDiscountsOnlyUnchangedCells(){let first=PlacementMap(bounds:CGRect(x:0,y:0,width:2,height:1),width:2,height:1,costs:[0.8,0.8]);let initial=TemporalStaleness.applying(to:first,previous:nil);let changed=PlacementMap(bounds:first.bounds,width:2,height:1,costs:[0.8,0.2]);let next=TemporalStaleness.applying(to:changed,previous:initial.state,decayPerObservation:0.25,floorMultiplier:0.5);XCTAssertEqual(next.map.costs[0],0.6,accuracy:0.001);XCTAssertEqual(next.map.costs[1],0.2,accuracy:0.001);XCTAssertEqual(next.state.unchangedCounts,[1,0])}
    func testTemporalStalenessNeverDropsBelowFloor(){let map=PlacementMap(bounds:CGRect(x:0,y:0,width:1,height:1),width:1,height:1,costs:[0.8]);var result=TemporalStaleness.applying(to:map,previous:nil);for _ in 0..<20 {result=TemporalStaleness.applying(to:map,previous:result.state,decayPerObservation:0.2,floorMultiplier:0.5)};XCTAssertEqual(result.map.costs[0],0.4,accuracy:0.001)}
}
